// SPDX-License-Identifier: MIT
pragma solidity ^0.8.24;

import "@openzeppelin/contracts/proxy/Clones.sol";
import "@openzeppelin/contracts/access/Ownable2Step.sol";
import "@openzeppelin/contracts/token/ERC20/IERC20.sol";
import "@openzeppelin/contracts/utils/ReentrancyGuard.sol";
import "@openzeppelin/contracts/utils/cryptography/ECDSA.sol";

import "./CustomToken.sol";
import "./LiquidityLocker.sol";
import "./interfaces/IUniswapV2Router02.sol";

/// @title CustomTokenFactory
/// @notice The entry point for the "advanced" launch path: creates a
/// CustomToken (EIP-1167 clone, same approach as TokenFactory/LaunchedToken)
/// with whatever fee configuration the creator chose — 0% tax is just the
/// all-zero case of the same contract — and seeds it with liquidity in the
/// same transaction, since none of a CustomToken's fee machinery (buy/sell
/// detection, auto-liquidity, reflections) means anything without a live
/// pool to trade against.
///
/// Deliberately a separate contract from TokenFactory rather than a third
/// mode bolted onto it — CustomToken is a meaningfully larger, more
/// complex contract (reflections, auto-liquidity, auto-burn) than
/// LaunchedToken, and keeping it fully separate means none of this touches
/// the already-audited-by-tests TokenFactory/LaunchedToken/LiquidityLocker
/// path at all. This factory uses its own LiquidityLocker instance (a
/// second deployment of the same, unmodified locker contract) rather than
/// sharing TokenFactory's, since a LiquidityLocker only ever accepts
/// lock() calls from the one factory address it was wired to.
///
/// The initial liquidity a creator provides at launch is locked to them
/// (same anti-rug protection as the main launch flow) — it's only the
/// *ongoing* auto-liquidity generated by the liquidity fee, after launch,
/// that gets burned outright (see CustomToken._processLiquidity).
contract CustomTokenFactory is Ownable2Step, ReentrancyGuard {
    address public immutable tokenImplementation;
    IUniswapV2Router02 public immutable router;
    LiquidityLocker public immutable locker;

    uint256 public deployFee; // "Deploy Custom Tax Token" — create + verify only, no liquidity, no tax of any kind
    uint256 public launchFee; // "Deploy and Add Liquidity (Live)" — atomic creation + pool + creator tax + platform tax
    address public feeTreasury;
    uint256 public lpLockDuration;

    // ---- platform-level graduating tax defaults, applied to every
    // CustomToken created after a change (existing tokens keep whatever
    // they were configured with — see CustomToken.configurePlatformTax).
    // This is entirely separate from, and on top of, whatever buy/sell tax
    // the creator themselves configured — same "platform always takes its
    // 0.25% until graduation" behavior TokenFactory already has for its
    // simpler token, now available here too. ----
    address public platformFeeWallet;
    uint256 public feeBps = 25; // 0.25%
    address public priceFeed;
    uint256 public graduationTargetUsd = 80_000; // whole dollars; tax permanently disables once a pool's live market cap crosses this
    uint256 public maxOracleStaleness = 1 hours;

    /// @notice PlatformRewardsDistributor's address — see
    /// TokenFactory.rewardsDistributor for the full explanation; behaves
    /// identically here. address(0) (the default) disables the feature
    /// entirely: deployFee/launchFee stay 100% feeTreasury, and every
    /// CustomToken launched from here on gets no reward diversion at all.
    address public rewardsDistributor;

    /// @notice Out of feeBps (the platform's own graduating tax on a
    /// CustomToken — entirely separate from the creator's own buyFees/
    /// sellFees), how much (absolute bps) gets diverted to
    /// rewardsDistributor instead of platformFeeWallet. See
    /// TokenFactory.rewardBps for the full explanation; behaves
    /// identically here.
    uint256 public rewardBps = 10; // 0.10%

    /// @notice CreatorRewardsDistributor's address — see
    /// TokenFactory.creatorRewardsDistributor for the full explanation;
    /// behaves identically here.
    address public creatorRewardsDistributor;

    /// @notice Out of feeBps, how much (absolute bps) gets diverted to
    /// creatorRewardsDistributor instead of platformFeeWallet — carved OUT
    /// OF feeBps, never added on top of it, and never overlapping
    /// rewardBps above. See TokenFactory.creatorRewardBps for the full
    /// explanation; behaves identically here.
    uint256 public creatorRewardBps = 5; // 0.05%

    /// @notice Anti-rug ceiling on a creator's own same-transaction buy-in,
    /// in bps of totalSupply_ — identical safeguard to TokenFactory's
    /// maxCreatorBuyBps, checked against the actual net tokens received
    /// (post buy-tax), not an estimate.
    uint256 public maxCreatorBuyBps = 500; // 5.00% by default

    /// @notice Slippage tolerance applied to addLiquidityETH()'s own
    /// amountTokenMin/amountETHMin — identical safeguard to TokenFactory's
    /// liquiditySlippageBps, protecting the initial liquidity seed against
    /// a bot manipulating the pair's reserves between submission and
    /// confirmation. The whole launch (liquidity add included) reverts if
    /// the actual amounts land outside this band. Owner-adjustable within a
    /// fixed 5.00%–8.00% band (see setLiquiditySlippageBps).
    uint256 public liquiditySlippageBps = 600; // 6.00% default, i.e. the midpoint of the allowed band
    uint256 public constant MIN_LIQUIDITY_SLIPPAGE_BPS = 500; // 5.00%
    uint256 public constant MAX_LIQUIDITY_SLIPPAGE_BPS = 800; // 8.00%

    /// @dev floor = amount minus liquiditySlippageBps of it.
    function _minWithSlippage(uint256 amount) private view returns (uint256) {
        return amount - (amount * liquiditySlippageBps) / 10_000;
    }

    /// @notice Same protection as liquiditySlippageBps, applied to the
    /// creator's own same-transaction buy-in instead of the liquidity add —
    /// see TokenFactory.buyInSlippageBps for the full reasoning, identical
    /// here. Owner-adjustable within the same fixed 5.00%–8.00% band.
    uint256 public buyInSlippageBps = 600; // 6.00% default, i.e. the midpoint of the allowed band

    /// @dev Standard Uniswap V2 constant-product quote — see
    /// TokenFactory._getAmountOut for the full reasoning, identical here.
    function _getAmountOut(uint256 amountIn, uint256 reserveIn, uint256 reserveOut) private pure returns (uint256) {
        uint256 amountInWithFee = amountIn * 997;
        uint256 numerator = amountInWithFee * reserveOut;
        uint256 denominator = reserveIn * 1000 + amountInWithFee;
        return numerator / denominator;
    }

    /// @dev Computes the buy-in's protective floor from the pool's own
    /// just-added reserves, netting out the tax this exact trade will pay
    /// FIRST (the creator's own configured buyFees, already recorded on
    /// `token` by initialize(), plus the platform's own tax if it ended up
    /// active — both read straight off the token's own getters rather than
    /// recomputed here, so this can never drift from what _update() will
    /// actually deduct), then applying buyInSlippageBps — returns whichever
    /// is stricter, that floor or the caller's own minCreatorTokensOut.
    function _effectiveMinBuyOut(
        address token,
        uint256 creatorBuyEthAmount,
        uint256 ethReserve,
        uint256 tokenReserve,
        uint256 callerMinOut
    ) private view returns (uint256) {
        (uint16 rBps, uint16 mBps, uint16 lBps, uint16 bBps) = CustomToken(payable(token)).buyFees();
        uint256 buyTaxBps = uint256(rBps) + mBps + lBps + bBps;
        if (CustomToken(payable(token)).platformTaxActive()) {
            buyTaxBps += CustomToken(payable(token)).platformFeeBps();
        }
        uint256 grossOut = _getAmountOut(creatorBuyEthAmount, ethReserve, tokenReserve);
        uint256 expectedNetOut = grossOut - (grossOut * buyTaxBps) / 10_000;
        uint256 floor = expectedNetOut - (expectedNetOut * buyInSlippageBps) / 10_000;
        return callerMinOut > floor ? callerMinOut : floor;
    }

    mapping(address => address) public creatorOf;
    mapping(address => address) public pairOf;
    address[] private _tokenList;
    mapping(address => address[]) private _tokensByCreator;

    // ---- gasless relayed launches — see TokenFactory's identical section
    // for the full explanation of the deposit/relay/settle flow and why
    // deposits are keyed by (depositor address, voucher hash). Duplicated
    // here rather than shared via a base contract, same reasoning as the
    // rest of this file's deliberate separation from TokenFactory. ----

    address public relayer;
    uint256 public maxRelayerGasReimbursementWei;
    uint256 public constant RELAY_GAS_OVERHEAD = 60_000;

    struct Deposit {
        uint256 amount;
        uint256 deadline;
        bool settled;
        bool reclaimed;
    }
    mapping(address => mapping(bytes32 => Deposit)) public deposits;

    struct CustomLaunchVoucher {
        address creator;
        string name;
        string symbol;
        uint256 totalSupply;
        bool addLiquidity;
        uint256 liquidityEthAmount;
        CustomToken.FeeSet buyFees;
        CustomToken.FeeSet sellFees;
        address reflectionAsset;
        address marketingWallet;
        uint256 creatorBuyEthAmount;
        uint256 minCreatorTokensOut;
        uint256 fee; // deployFee or launchFee the creator locked in and escrowed at deposit time
        uint256 salt;
        uint256 deadline;
    }

    bytes32 private constant FEE_SET_TYPEHASH =
        keccak256("FeeSet(uint16 reflectionBps,uint16 marketingBps,uint16 liquidityBps,uint16 burnBps)");

    bytes32 private constant CUSTOM_LAUNCH_VOUCHER_TYPEHASH = keccak256(
        "CustomLaunchVoucher(address creator,string name,string symbol,uint256 totalSupply,bool addLiquidity,uint256 liquidityEthAmount,FeeSet buyFees,FeeSet sellFees,address reflectionAsset,address marketingWallet,uint256 creatorBuyEthAmount,uint256 minCreatorTokensOut,uint256 fee,uint256 salt,uint256 deadline)FeeSet(uint16 reflectionBps,uint16 marketingBps,uint16 liquidityBps,uint16 burnBps)"
    );

    // Hand-rolled EIP-712 domain separator — see TokenFactory for why this
    // avoids OpenZeppelin's EIP712 base (mcopy/Cancun dependency).
    bytes32 private constant EIP712_DOMAIN_TYPEHASH = keccak256(
        "EIP712Domain(string name,string version,uint256 chainId,address verifyingContract)"
    );
    bytes32 private immutable _domainSeparator;

    event RelayerUpdated(address newRelayer);
    event MaxRelayerGasReimbursementUpdated(uint256 newCapWei);
    event LaunchDeposited(bytes32 indexed voucherHash, address indexed creator, uint256 amount, uint256 deadline);
    event DepositReclaimed(bytes32 indexed voucherHash, address indexed creator, uint256 amount);
    event RelayedFeeSettled(
        bytes32 indexed voucherHash,
        address indexed token,
        uint256 feeCollected,
        uint256 gasReimbursed,
        uint256 toTreasury,
        uint256 toRewards
    );

    modifier onlyRelayer() {
        require(msg.sender == relayer, "CustomTokenFactory: caller is not the relayer");
        _;
    }

    event CustomTokenCreated(
        address indexed token,
        address indexed creator,
        string name,
        string symbol,
        uint256 totalSupply,
        address pair,
        address reflectionAsset,
        address marketingWallet
    );
    event InitialLiquidityLocked(address indexed token, uint256 lpAmount, uint256 unlockTime, uint256 indexed lockId);
    event CreatorBought(address indexed token, address indexed creator, uint256 ethIn, uint256 tokensOut);
    event DeployFeeUpdated(uint256 newFee);
    event LaunchFeeUpdated(uint256 newFee);
    event FeeTreasuryUpdated(address newTreasury);
    event LpLockDurationUpdated(uint256 newDuration);
    event MaxCreatorBuyBpsUpdated(uint256 newBps);
    event LiquiditySlippageBpsUpdated(uint256 newBps);
    event BuyInSlippageBpsUpdated(uint256 newBps);
    event TaxDefaultsUpdated();
    event RewardsDistributorUpdated(address newDistributor);
    event CreatorRewardsDistributorUpdated(address newDistributor);
    event TokenPriceFeedUpdated(address indexed token, address newPriceFeed, uint256 newMaxOracleStaleness);

    constructor(
        address tokenImplementation_,
        address router_,
        address locker_,
        uint256 deployFee_,
        uint256 launchFee_,
        address feeTreasury_,
        uint256 lpLockDuration_,
        address platformFeeWallet_,
        address priceFeed_
    ) Ownable(msg.sender) {
        require(tokenImplementation_ != address(0), "CustomTokenFactory: invalid implementation");
        require(router_ != address(0), "CustomTokenFactory: invalid router");
        require(locker_ != address(0), "CustomTokenFactory: invalid locker");
        require(feeTreasury_ != address(0), "CustomTokenFactory: invalid treasury");

        tokenImplementation = tokenImplementation_;
        router = IUniswapV2Router02(router_);
        locker = LiquidityLocker(locker_);
        deployFee = deployFee_;
        launchFee = launchFee_;
        feeTreasury = feeTreasury_;
        lpLockDuration = lpLockDuration_;
        platformFeeWallet = platformFeeWallet_;
        priceFeed = priceFeed_;

        _domainSeparator = keccak256(
            abi.encode(
                EIP712_DOMAIN_TYPEHASH,
                keccak256(bytes("HoodLaunchCustomTokenFactory")),
                keccak256(bytes("1")),
                block.chainid,
                address(this)
            )
        );
    }

    function _hashTypedDataV4(bytes32 structHash) private view returns (bytes32) {
        return keccak256(abi.encodePacked("\x19\x01", _domainSeparator, structHash));
    }

    function _hashFeeSet(CustomToken.FeeSet calldata f) private pure returns (bytes32) {
        return keccak256(abi.encode(FEE_SET_TYPEHASH, f.reflectionBps, f.marketingBps, f.liquidityBps, f.burnBps));
    }

    /// @notice Computes the exact EIP-712 digest a creator must sign to
    /// authorize a relayed CustomToken launch. See TokenFactory.
    /// hashLaunchVoucher for the full explanation.
    function hashCustomLaunchVoucher(CustomLaunchVoucher calldata voucher) public view returns (bytes32) {
        bytes32 structHash = keccak256(
            abi.encode(
                CUSTOM_LAUNCH_VOUCHER_TYPEHASH,
                voucher.creator,
                keccak256(bytes(voucher.name)),
                keccak256(bytes(voucher.symbol)),
                voucher.totalSupply,
                voucher.addLiquidity,
                voucher.liquidityEthAmount,
                _hashFeeSet(voucher.buyFees),
                _hashFeeSet(voucher.sellFees),
                voucher.reflectionAsset,
                voucher.marketingWallet,
                voucher.creatorBuyEthAmount,
                voucher.minCreatorTokensOut,
                voucher.fee,
                voucher.salt,
                voucher.deadline
            )
        );
        return _hashTypedDataV4(structHash);
    }

    /// @notice Step 2 of a relayed launch — see TokenFactory.
    /// depositForRelayedLaunch for the full explanation; behaves
    /// identically here.
    function depositForRelayedLaunch(bytes32 voucherHash, uint256 deadline) external payable nonReentrant {
        require(msg.value > 0, "CustomTokenFactory: no ETH sent");
        require(deadline > block.timestamp, "CustomTokenFactory: deadline already passed");
        Deposit storage d = deposits[msg.sender][voucherHash];
        require(d.amount == 0, "CustomTokenFactory: voucher already funded");
        d.amount = msg.value;
        d.deadline = deadline;
        emit LaunchDeposited(voucherHash, msg.sender, msg.value, deadline);
    }

    /// @notice See TokenFactory.reclaimDeposit.
    function reclaimDeposit(bytes32 voucherHash) external nonReentrant {
        Deposit storage d = deposits[msg.sender][voucherHash];
        require(d.amount > 0, "CustomTokenFactory: no such deposit");
        require(!d.settled, "CustomTokenFactory: voucher already relayed");
        require(!d.reclaimed, "CustomTokenFactory: already reclaimed");
        require(block.timestamp > d.deadline, "CustomTokenFactory: deadline has not passed yet");
        d.reclaimed = true;
        uint256 amount = d.amount;
        (bool sent, ) = payable(msg.sender).call{value: amount}("");
        require(sent, "CustomTokenFactory: refund transfer failed");
        emit DepositReclaimed(voucherHash, msg.sender, amount);
    }

    /// @notice Step 3 of a relayed launch, called only by the trusted
    /// relayer — see TokenFactory.relayedCreateToken for the full
    /// explanation of the verification, deploy, and gas-then-split
    /// settlement steps. Mirrors createCustomToken()'s two modes with
    /// voucher.creator standing in everywhere createCustomToken() used
    /// msg.sender.
    function relayedCreateCustomToken(
        CustomLaunchVoucher calldata voucher,
        bytes calldata signature
    )
        external
        onlyRelayer
        nonReentrant
        returns (address token, address pair, uint256 lpAmount, uint256 lockId, uint256 creatorTokensBought)
    {
        uint256 gasStart = gasleft();

        require(block.timestamp <= voucher.deadline, "CustomTokenFactory: voucher expired");
        require(bytes(voucher.name).length > 0, "CustomTokenFactory: name required");
        require(bytes(voucher.symbol).length > 0, "CustomTokenFactory: symbol required");
        require(voucher.totalSupply > 0, "CustomTokenFactory: supply must be > 0");

        bytes32 voucherHash = hashCustomLaunchVoucher(voucher);
        address signer = ECDSA.recover(voucherHash, signature);
        require(signer == voucher.creator, "CustomTokenFactory: signature does not match voucher creator");

        Deposit storage d = deposits[voucher.creator][voucherHash];
        require(d.amount > 0, "CustomTokenFactory: no matching deposit");
        require(!d.settled, "CustomTokenFactory: voucher already relayed");
        require(!d.reclaimed, "CustomTokenFactory: deposit already reclaimed");
        require(block.timestamp <= d.deadline, "CustomTokenFactory: deposit expired, creator must reclaim");

        uint256 expectedDeposit = voucher.fee +
            (voucher.addLiquidity ? voucher.liquidityEthAmount + voucher.creatorBuyEthAmount : 0);
        require(d.amount == expectedDeposit, "CustomTokenFactory: deposit does not match voucher amount");

        d.settled = true; // effects before interactions

        token = Clones.clone(tokenImplementation);

        if (!voucher.addLiquidity) {
            require(
                voucher.liquidityEthAmount == 0 && voucher.creatorBuyEthAmount == 0,
                "CustomTokenFactory: no liquidity/buy-in in deploy-only mode"
            );
            CustomToken(payable(token)).initialize(
                voucher.name,
                voucher.symbol,
                voucher.totalSupply,
                voucher.creator,
                voucher.creator,
                address(this),
                address(router),
                voucher.buyFees,
                voucher.sellFees,
                voucher.reflectionAsset,
                voucher.marketingWallet
            );
        } else {
            require(voucher.liquidityEthAmount > 0, "CustomTokenFactory: no ETH sent for liquidity");
            CustomToken(payable(token)).initialize(
                voucher.name,
                voucher.symbol,
                voucher.totalSupply,
                voucher.creator,
                address(this),
                address(this),
                address(router),
                voucher.buyFees,
                voucher.sellFees,
                voucher.reflectionAsset,
                voucher.marketingWallet
            );

            (pair, lpAmount, lockId, creatorTokensBought) = _relayedSeedLiquidityAndBuyIn(
                token,
                voucher.creator,
                voucher.totalSupply,
                voucher.liquidityEthAmount,
                voucher.creatorBuyEthAmount,
                voucher.minCreatorTokensOut
            );
            pairOf[token] = pair;
        }

        creatorOf[token] = voucher.creator;
        _tokensByCreator[voucher.creator].push(token);
        _tokenList.push(token);

        emit CustomTokenCreated(
            token, voucher.creator, voucher.name, voucher.symbol, voucher.totalSupply, pair, voucher.reflectionAsset, voucher.marketingWallet
        );

        _settleRelayedFee(voucherHash, token, voucher.fee, gasStart);
    }

    /// @dev Relayed counterpart to _seedLiquidityAndBuyIn — identical
    /// behavior, parameterized on an explicit `creator_` everywhere the
    /// original used msg.sender.
    function _relayedSeedLiquidityAndBuyIn(
        address token,
        address creator_,
        uint256 totalSupply_,
        uint256 liquidityEthAmount,
        uint256 creatorBuyEthAmount,
        uint256 minCreatorTokensOut
    ) internal returns (address pair, uint256 lpAmount, uint256 lockId, uint256 creatorTokensBought) {
        IERC20(token).approve(address(router), totalSupply_);
        (uint256 amountTokenUsed, uint256 amountETHUsed, uint256 lpAmountAdded) = router.addLiquidityETH{value: liquidityEthAmount}(
            token,
            totalSupply_,
            _minWithSlippage(totalSupply_),
            _minWithSlippage(liquidityEthAmount),
            address(locker),
            block.timestamp + 15 minutes
        );
        lpAmount = lpAmountAdded;

        pair = IUniswapV2FactoryMinimal(router.factory()).getPair(token, router.WETH());
        require(pair != address(0), "CustomTokenFactory: pair not found after addLiquidityETH");
        CustomToken(payable(token)).setPair(pair);

        uint256 effectiveRewardBps = rewardsDistributor != address(0) ? rewardBps : 0;
        uint256 effectiveCreatorRewardBps = creatorRewardsDistributor != address(0) ? creatorRewardBps : 0;
        CustomToken(payable(token)).configurePlatformTax(
            platformFeeWallet, feeBps, priceFeed, graduationTargetUsd, maxOracleStaleness,
            rewardsDistributor, effectiveRewardBps, creatorRewardsDistributor, effectiveCreatorRewardBps
        );

        uint256 unlockTime = block.timestamp + lpLockDuration;
        lockId = locker.lock(pair, creator_, lpAmount, unlockTime);
        emit InitialLiquidityLocked(token, lpAmount, unlockTime, lockId);

        if (creatorBuyEthAmount > 0) {
            address[] memory path = new address[](2);
            path[0] = router.WETH();
            path[1] = token;
            uint256 effectiveMinOut = _effectiveMinBuyOut(token, creatorBuyEthAmount, amountETHUsed, amountTokenUsed, minCreatorTokensOut);
            uint256 balBefore = IERC20(token).balanceOf(creator_);
            router.swapExactETHForTokensSupportingFeeOnTransferTokens{value: creatorBuyEthAmount}(
                effectiveMinOut,
                path,
                creator_,
                block.timestamp + 15 minutes
            );
            creatorTokensBought = IERC20(token).balanceOf(creator_) - balBefore;
            require(
                creatorTokensBought <= (totalSupply_ * maxCreatorBuyBps) / 10_000,
                "CustomTokenFactory: creator buy-in exceeds max allowed share of supply"
            );
            emit CreatorBought(token, creator_, creatorBuyEthAmount, creatorTokensBought);
        }
    }

    /// @dev Gas-then-split settlement for a relayed launch — see
    /// TokenFactory._settleRelayedFee for the full explanation.
    function _settleRelayedFee(bytes32 voucherHash, address token, uint256 feeCollected, uint256 gasStart) internal {
        if (feeCollected == 0) return;

        uint256 gasUsed = (gasStart - gasleft()) + RELAY_GAS_OVERHEAD;
        uint256 gasReimbursement = gasUsed * tx.gasprice;
        if (maxRelayerGasReimbursementWei > 0 && gasReimbursement > maxRelayerGasReimbursementWei) {
            gasReimbursement = maxRelayerGasReimbursementWei;
        }
        if (gasReimbursement > feeCollected) {
            gasReimbursement = feeCollected;
        }

        if (gasReimbursement > 0) {
            (bool sentGas, ) = payable(relayer).call{value: gasReimbursement}("");
            require(sentGas, "CustomTokenFactory: relayer gas reimbursement failed");
        }

        uint256 netFee = feeCollected - gasReimbursement;
        uint256 toRewards;
        uint256 toTreasury;
        if (netFee > 0) {
            if (rewardsDistributor != address(0)) {
                toRewards = netFee / 2;
                toTreasury = netFee - toRewards;
                if (toRewards > 0) {
                    (bool sentRewards, ) = rewardsDistributor.call{value: toRewards}("");
                    require(sentRewards, "CustomTokenFactory: rewards transfer failed");
                }
                (bool sent, ) = feeTreasury.call{value: toTreasury}("");
                require(sent, "CustomTokenFactory: fee transfer failed");
            } else {
                toTreasury = netFee;
                (bool sent, ) = feeTreasury.call{value: netFee}("");
                require(sent, "CustomTokenFactory: fee transfer failed");
            }
        }

        emit RelayedFeeSettled(voucherHash, token, feeCollected, gasReimbursement, toTreasury, toRewards);
    }

    /// @notice Deploy a new CustomToken and seed its pool, atomically.
    /// msg.value must equal deployFee + liquidityEthAmount +
    /// creatorBuyEthAmount exactly. buyFees_/sellFees_ are each capped at
    /// 5% total (see CustomToken.MAX_TOTAL_BPS) — passing all-zero fees is
    /// exactly how you get a 0%-tax token through this same path.
    /// reflectionAsset_ == address(0) means reflections pay out in native
    /// ETH; any other address is the ERC20 they pay out in instead.
    /// marketingWallet_ is required only if either side's marketingBps is
    /// nonzero. creatorBuyEthAmount is optional (0 skips it entirely) — an
    /// ordinary swap against the pool just created, in this same
    /// transaction, guaranteed to be its first trade, but capped at
    /// maxCreatorBuyBps of totalSupply_ (checked against what actually
    /// lands net of buy tax) as an anti-rug safeguard: exceeding it reverts
    /// the whole launch rather than partially executing.
    function createCustomToken(
        string calldata name_,
        string calldata symbol_,
        uint256 totalSupply_,
        bool addLiquidity,
        uint256 liquidityEthAmount,
        CustomToken.FeeSet calldata buyFees_,
        CustomToken.FeeSet calldata sellFees_,
        address reflectionAsset_,
        address marketingWallet_,
        uint256 creatorBuyEthAmount,
        uint256 minCreatorTokensOut
    ) external payable nonReentrant returns (address token, address pair, uint256 lpAmount, uint256 lockId, uint256 creatorTokensBought) {
        require(bytes(name_).length > 0, "CustomTokenFactory: name required");
        require(bytes(symbol_).length > 0, "CustomTokenFactory: symbol required");
        require(totalSupply_ > 0, "CustomTokenFactory: supply must be > 0");

        token = Clones.clone(tokenImplementation);
        uint256 feeCollected;

        if (!addLiquidity) {
            // "Deploy Custom Tax Token": create + verify only, no pool ever
            // gets seeded — pair stays address(0) forever, so neither the
            // creator's own configured tax nor the platform's graduating
            // tax can ever activate (both gate on _update() seeing a
            // nonzero pair). Whatever buyFees_/sellFees_ the creator chose
            // are recorded on-chain for transparency, but are inert unless
            // this token is later paired manually — entirely the creator's
            // own responsibility from here, same as TokenFactory's plain
            // "Deploy Token" mode.
            require(msg.value == deployFee, "CustomTokenFactory: incorrect ETH sent for Deploy Custom Tax Token");
            require(liquidityEthAmount == 0 && creatorBuyEthAmount == 0, "CustomTokenFactory: no liquidity/buy-in in deploy-only mode");
            feeCollected = deployFee;
            CustomToken(payable(token)).initialize(
                name_,
                symbol_,
                totalSupply_,
                msg.sender,
                msg.sender,
                address(this),
                address(router),
                buyFees_,
                sellFees_,
                reflectionAsset_,
                marketingWallet_
            );
        } else {
            // "Deploy and Add Liquidity (Live)": the only path where either
            // the creator's own tax or the platform's 0.25%-until-
            // graduation tax can ever apply — both require a live pair,
            // which only this branch creates.
            require(msg.value >= launchFee, "CustomTokenFactory: launch fee not met");
            require(
                msg.value - launchFee == liquidityEthAmount + creatorBuyEthAmount,
                "CustomTokenFactory: msg.value doesn't match fee + liquidity + buy-in"
            );
            require(liquidityEthAmount > 0, "CustomTokenFactory: no ETH sent for liquidity");
            feeCollected = launchFee;
            CustomToken(payable(token)).initialize(
                name_,
                symbol_,
                totalSupply_,
                msg.sender,
                address(this),
                address(this),
                address(router),
                buyFees_,
                sellFees_,
                reflectionAsset_,
                marketingWallet_
            );

            (pair, lpAmount, lockId, creatorTokensBought) = _seedLiquidityAndBuyIn(
                token,
                totalSupply_,
                liquidityEthAmount,
                creatorBuyEthAmount,
                minCreatorTokensOut
            );
            pairOf[token] = pair;
        }

        // Effects before interactions: every piece of this factory's own
        // state for `token` is finalized before the external fee-transfer
        // call below, so a reentrant call during it (e.g. a malicious or
        // buggy feeTreasury) can never observe this launch half-recorded.
        creatorOf[token] = msg.sender;
        _tokensByCreator[msg.sender].push(token);
        _tokenList.push(token);

        if (feeCollected > 0) {
            // 50% of every deployFee/launchFee stays platform profit exactly
            // as before; the other 50% funds the platform's own buyback/
            // burn/holder-rewards contract, once one is configured — see
            // TokenFactory._finalizeLaunch for the identical logic on the
            // simpler token path. While rewardsDistributor is unset, this
            // is 100% feeTreasury, byte-for-byte the same behavior this
            // contract has always had.
            if (rewardsDistributor != address(0)) {
                uint256 toRewards = feeCollected / 2;
                uint256 toTreasury = feeCollected - toRewards;
                if (toRewards > 0) {
                    (bool sentRewards, ) = rewardsDistributor.call{value: toRewards}("");
                    require(sentRewards, "CustomTokenFactory: rewards transfer failed");
                }
                (bool sent, ) = feeTreasury.call{value: toTreasury}("");
                require(sent, "CustomTokenFactory: fee transfer failed");
            } else {
                (bool sent, ) = feeTreasury.call{value: feeCollected}("");
                require(sent, "CustomTokenFactory: fee transfer failed");
            }
        }

        emit CustomTokenCreated(token, msg.sender, name_, symbol_, totalSupply_, pair, reflectionAsset_, marketingWallet_);
    }

    /// @dev Everything specific to seeding the pool and the optional
    /// buy-in, split out of createCustomToken() to keep its stack shallow
    /// enough to compile — same reason TokenFactory splits
    /// _launchWithLiquidity out of createToken(). Only ever called from the
    /// addLiquidity branch above.
    function _seedLiquidityAndBuyIn(
        address token,
        uint256 totalSupply_,
        uint256 liquidityEthAmount,
        uint256 creatorBuyEthAmount,
        uint256 minCreatorTokensOut
    ) internal returns (address pair, uint256 lpAmount, uint256 lockId, uint256 creatorTokensBought) {
        IERC20(token).approve(address(router), totalSupply_);
        (uint256 amountTokenUsed, uint256 amountETHUsed, uint256 lpAmountAdded) = router.addLiquidityETH{value: liquidityEthAmount}(
            token,
            totalSupply_,
            _minWithSlippage(totalSupply_), // 5–8% slippage tolerance — see liquiditySlippageBps
            _minWithSlippage(liquidityEthAmount),
            address(locker), // LP tokens mint straight to the locker — never pass through this factory
            block.timestamp + 15 minutes
        );
        lpAmount = lpAmountAdded;

        pair = IUniswapV2FactoryMinimal(router.factory()).getPair(token, router.WETH());
        require(pair != address(0), "CustomTokenFactory: pair not found after addLiquidityETH");
        CustomToken(payable(token)).setPair(pair);

        // Wire the platform's own graduating tax on top of whatever the
        // creator configured — same 0.25%-until-graduation behavior as
        // TokenFactory's simpler token, just skimmed in-kind rather than
        // batched. Leaving platformFeeWallet/priceFeed unset simply leaves
        // this permanently inactive (see CustomToken.configurePlatformTax);
        // it never blocks a launch the way TokenFactory's mandatory
        // platform fee wallet/price feed checks do.
        // rewardBps only ever actually applies once rewardsDistributor is
        // set — see TokenFactory._launchWithLiquidity for the identical
        // reasoning on the simpler token path.
        uint256 effectiveRewardBps = rewardsDistributor != address(0) ? rewardBps : 0;
        uint256 effectiveCreatorRewardBps = creatorRewardsDistributor != address(0) ? creatorRewardBps : 0;
        CustomToken(payable(token)).configurePlatformTax(
            platformFeeWallet, feeBps, priceFeed, graduationTargetUsd, maxOracleStaleness,
            rewardsDistributor, effectiveRewardBps, creatorRewardsDistributor, effectiveCreatorRewardBps
        );

        uint256 unlockTime = block.timestamp + lpLockDuration;
        lockId = locker.lock(pair, msg.sender, lpAmount, unlockTime);
        emit InitialLiquidityLocked(token, lpAmount, unlockTime, lockId);

        if (creatorBuyEthAmount > 0) {
            address[] memory path = new address[](2);
            path[0] = router.WETH();
            path[1] = token;
            uint256 effectiveMinOut = _effectiveMinBuyOut(token, creatorBuyEthAmount, amountETHUsed, amountTokenUsed, minCreatorTokensOut);
            uint256 balBefore = IERC20(token).balanceOf(msg.sender);
            router.swapExactETHForTokensSupportingFeeOnTransferTokens{value: creatorBuyEthAmount}(
                effectiveMinOut,
                path,
                msg.sender,
                block.timestamp + 15 minutes
            );
            creatorTokensBought = IERC20(token).balanceOf(msg.sender) - balBefore;
            require(
                creatorTokensBought <= (totalSupply_ * maxCreatorBuyBps) / 10_000,
                "CustomTokenFactory: creator buy-in exceeds max allowed share of supply"
            );
            emit CreatorBought(token, msg.sender, creatorBuyEthAmount, creatorTokensBought);
        }
    }

    function tokensOf(address creator_) external view returns (address[] memory) {
        return _tokensByCreator[creator_];
    }

    function allTokens() external view returns (address[] memory) {
        return _tokenList;
    }

    // ---- admin ----

    /// @notice Updates the flat fee for "Deploy Custom Tax Token" (no
    /// liquidity, no tax of any kind). See TokenFactory.setDeployFee for
    /// why this is a fixed wei amount rather than USD-denominated.
    function setDeployFee(uint256 newFee) external onlyOwner {
        deployFee = newFee;
        emit DeployFeeUpdated(newFee);
    }

    /// @notice Updates the flat fee for "Deploy and Add Liquidity (Live)",
    /// charged on top of the liquidity/buy-in ETH.
    function setLaunchFee(uint256 newFee) external onlyOwner {
        launchFee = newFee;
        emit LaunchFeeUpdated(newFee);
    }

    function setFeeTreasury(address newTreasury) external onlyOwner {
        require(newTreasury != address(0), "CustomTokenFactory: invalid treasury");
        feeTreasury = newTreasury;
        emit FeeTreasuryUpdated(newTreasury);
    }

    function setLpLockDuration(uint256 newDuration) external onlyOwner {
        lpLockDuration = newDuration;
        emit LpLockDurationUpdated(newDuration);
    }

    /// @notice Updates the anti-rug ceiling on a creator's own
    /// same-transaction buy-in, in bps of totalSupply_ (500 = 5.00%).
    /// Applies to launches from this point forward.
    function setMaxCreatorBuyBps(uint256 newBps) external onlyOwner {
        require(newBps <= 10_000, "CustomTokenFactory: bps cannot exceed 100%");
        maxCreatorBuyBps = newBps;
        emit MaxCreatorBuyBpsUpdated(newBps);
    }

    /// @notice Adjusts the addLiquidityETH slippage tolerance, kept to a
    /// fixed 5.00%–8.00% band — see TokenFactory.setLiquiditySlippageBps for
    /// the full reasoning, identical here.
    function setLiquiditySlippageBps(uint256 newBps) external onlyOwner {
        require(newBps >= MIN_LIQUIDITY_SLIPPAGE_BPS, "CustomTokenFactory: slippage below 5% floor");
        require(newBps <= MAX_LIQUIDITY_SLIPPAGE_BPS, "CustomTokenFactory: slippage above 8% ceiling");
        liquiditySlippageBps = newBps;
        emit LiquiditySlippageBpsUpdated(newBps);
    }

    /// @notice Adjusts the creator buy-in's slippage tolerance, same fixed
    /// 5.00%–8.00% band as setLiquiditySlippageBps, for the same reasons.
    function setBuyInSlippageBps(uint256 newBps) external onlyOwner {
        require(newBps >= MIN_LIQUIDITY_SLIPPAGE_BPS, "CustomTokenFactory: slippage below 5% floor");
        require(newBps <= MAX_LIQUIDITY_SLIPPAGE_BPS, "CustomTokenFactory: slippage above 8% ceiling");
        buyInSlippageBps = newBps;
        emit BuyInSlippageBpsUpdated(newBps);
    }

    /// @notice Points deployFee/launchFee's 50% rewards share, and every
    /// future CustomToken's per-token reward diversion, at a
    /// PlatformRewardsDistributor. See TokenFactory.setRewardsDistributor —
    /// behaves identically here. address(0) disables the entire feature,
    /// fully reversibly, and never touches a token or launch that already
    /// happened.
    function setRewardsDistributor(address newDistributor) external onlyOwner {
        rewardsDistributor = newDistributor;
        emit RewardsDistributorUpdated(newDistributor);
    }

    /// @notice See TokenFactory.setCreatorRewardsDistributor — identical
    /// behavior here.
    function setCreatorRewardsDistributor(address newDistributor) external onlyOwner {
        creatorRewardsDistributor = newDistributor;
        emit CreatorRewardsDistributorUpdated(newDistributor);
    }

    /// @notice See TokenFactory.setRelayer — identical behavior here.
    function setRelayer(address newRelayer) external onlyOwner {
        relayer = newRelayer;
        emit RelayerUpdated(newRelayer);
    }

    /// @notice See TokenFactory.setMaxRelayerGasReimbursement — identical
    /// behavior here.
    function setMaxRelayerGasReimbursement(uint256 newCapWei) external onlyOwner {
        maxRelayerGasReimbursementWei = newCapWei;
        emit MaxRelayerGasReimbursementUpdated(newCapWei);
    }

    /// @notice Update the platform tax defaults applied to CustomTokens
    /// created from this point forward. Existing tokens are unaffected —
    /// each one snapshots these values into its own storage the moment
    /// configurePlatformTax() runs during its own launch.
    /// platformFeeWallet_ and priceFeed_ may still be set to address(0)
    /// deliberately — that's the documented way to leave the platform tax
    /// permanently inactive for launches going forward (configurePlatformTax
    /// treats a zero feeWallet/feeBps as "record it, but never activate it";
    /// unlike TokenFactory, this never blocks a launch). feeBps_,
    /// graduationTargetUsd_, and maxOracleStaleness_ get real bounds below
    /// so a mistyped value can't silently brick every future launch's
    /// transfers (feeBps_ above 10,000) or defeat the tax from block one
    /// (graduationTargetUsd_ == 0) — mirrors the same bound already
    /// enforced on setMaxCreatorBuyBps, and the identical fix applied to
    /// TokenFactory.setTaxDefaults. rewardBps_ is the new addition: how
    /// much of feeBps_ gets carved off to rewardsDistributor going
    /// forward — must never exceed feeBps_ itself.
    function setTaxDefaults(
        address platformFeeWallet_,
        uint256 feeBps_,
        address priceFeed_,
        uint256 graduationTargetUsd_,
        uint256 maxOracleStaleness_,
        uint256 rewardBps_,
        uint256 creatorRewardBps_
    ) external onlyOwner {
        require(feeBps_ <= 10_000, "CustomTokenFactory: feeBps cannot exceed 100%");
        require(graduationTargetUsd_ > 0, "CustomTokenFactory: graduation target must be > 0");
        require(maxOracleStaleness_ > 0, "CustomTokenFactory: oracle staleness must be > 0");
        require(rewardBps_ + creatorRewardBps_ <= feeBps_, "CustomTokenFactory: rewardBps+creatorRewardBps cannot exceed feeBps");
        platformFeeWallet = platformFeeWallet_;
        feeBps = feeBps_;
        priceFeed = priceFeed_;
        graduationTargetUsd = graduationTargetUsd_;
        maxOracleStaleness = maxOracleStaleness_;
        rewardBps = rewardBps_;
        creatorRewardBps = creatorRewardBps_;
        emit TaxDefaultsUpdated();
    }

    /// @notice Escape hatch for an already-launched CustomToken whose
    /// platform price feed has gone permanently stale or was never a real,
    /// maintained feed — see CustomToken.updatePriceFeed /
    /// TokenFactory.updateTokenPriceFeed (identical pattern). Owner-only,
    /// and deliberately narrow: repoints only that token's oracle inputs,
    /// never its fee rates, fee wallet, pair, or platformTaxActive
    /// directly.
    function updateTokenPriceFeed(address token, address newPriceFeed_, uint256 newMaxOracleStaleness_) external onlyOwner {
        CustomToken(payable(token)).updatePriceFeed(newPriceFeed_, newMaxOracleStaleness_);
        emit TokenPriceFeedUpdated(token, newPriceFeed_, newMaxOracleStaleness_);
    }
}
